### ISSUE TITLE
ownership access?

### ISSUE THREAD

**Issue by gabrielcsapo** [vorpaljs/bash-codegen#1]
☹️ I can't push my code without access...

**Comment by gabrielcsapo** [comment]
@parro-it @dthree @vorpaljs

**Comment by parro-it** [comment]
I removed and readded you, you should receive a confirmation mail

**Comment by gabrielcsapo** [comment]
Got it! Will push what I have tomorrow!

**Comment by gabrielcsapo** [comment]
Thank you @parro-it
